/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20260128T185554"   // DateTime using ISO-8601 format
        " "                 // alignment
        "162914e5"          // STLIB commit
        "--------"          // ADJ commit
        "30af45bb"          // Board commit
        // the '=' is used for unparsing
        ;
}