/*
* AUTOGENERATED FILE
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))=
        "****************"  // placeholder for beggining
        "20260429T233048"   // DateTime using ISO-8601 format
        " "                 // alignment
        "a6be4c87"          // STLIB commit
        "--------"          // ADJ commit
        "484c6a5e"          // Board commit
        // the '=' is used for unparsing
        ;
}