#pragma once
#include "ST-LIB.hpp"

/*Data packets for HVBMS
-AUTOGENERATED CODE, DO NOT MODIFY-*/
class DataPackets{
public:
    enum class sdc_status : uint8_t
    {
        ENGAGED = 0,
        DISENGAGED = 1,
    };
    enum class gsm_status : uint8_t
    {
        CONNECTING = 0,
        OPERATIONAL = 1,
    };
    enum class imd_status : uint8_t
    {
        SHORTCIRCUIT = 0,
        NORMAL = 1,
        UNDERVOLTAGE = 2,
        FAST_EVAL = 3,
        EQUIPMENT_FAULT = 4,
        GROUNDING_FAULT = 5,
    };
    enum class nested_sm_status : uint8_t
    {
        PRECHARGE = 0,
        OPERATIONAL = 1,
    };
    

    static void batteries_voltage_init(float &batteries_voltage_reading)
    {
        batteries_voltage_packet = new HeapPacket(static_cast<uint16_t>(928), &batteries_voltage_reading);
    }

    static void voltage_sensor_init(float &voltage_reading)
    {
        voltage_sensor_packet = new HeapPacket(static_cast<uint16_t>(930), &voltage_reading);
    }

    static void current_sensor_init(float &current_reading)
    {
        current_sensor_packet = new HeapPacket(static_cast<uint16_t>(931), &current_reading);
    }

    static void sdc_init(sdc_status &sdc_status)
    {
        sdc_packet = new HeapPacket(static_cast<uint16_t>(944), &sdc_status);
    }

    static void battery_1_init(float &battery1_cell1, float &battery1_cell2, float &battery1_cell3, float &battery1_cell4, float &battery1_cell5, float &battery1_cell6, float &battery1_cell7, float &battery1_cell8, float &battery1_cell9, float &battery1_cell10, float &battery1_cell11, float &battery1_cell12, float &battery1_total_voltage, float &battery1_max_temp, float &battery1_min_temp)
    {
        battery_1_packet = new HeapPacket(static_cast<uint16_t>(910), &battery1_cell1, &battery1_cell2, &battery1_cell3, &battery1_cell4, &battery1_cell5, &battery1_cell6, &battery1_cell7, &battery1_cell8, &battery1_cell9, &battery1_cell10, &battery1_cell11, &battery1_cell12, &battery1_total_voltage, &battery1_max_temp, &battery1_min_temp);
    }

    static void battery_2_init(float &battery2_cell1, float &battery2_cell2, float &battery2_cell3, float &battery2_cell4, float &battery2_cell5, float &battery2_cell6, float &battery2_cell7, float &battery2_cell8, float &battery2_cell9, float &battery2_cell10, float &battery2_cell11, float &battery2_cell12, float &battery2_total_voltage, float &battery2_max_temp, float &battery2_min_temp)
    {
        battery_2_packet = new HeapPacket(static_cast<uint16_t>(911), &battery2_cell1, &battery2_cell2, &battery2_cell3, &battery2_cell4, &battery2_cell5, &battery2_cell6, &battery2_cell7, &battery2_cell8, &battery2_cell9, &battery2_cell10, &battery2_cell11, &battery2_cell12, &battery2_total_voltage, &battery2_max_temp, &battery2_min_temp);
    }

    static void battery_3_init(float &battery3_cell1, float &battery3_cell2, float &battery3_cell3, float &battery3_cell4, float &battery3_cell5, float &battery3_cell6, float &battery3_cell7, float &battery3_cell8, float &battery3_cell9, float &battery3_cell10, float &battery3_cell11, float &battery3_cell12, float &battery3_total_voltage, float &battery3_max_temp, float &battery3_min_temp)
    {
        battery_3_packet = new HeapPacket(static_cast<uint16_t>(912), &battery3_cell1, &battery3_cell2, &battery3_cell3, &battery3_cell4, &battery3_cell5, &battery3_cell6, &battery3_cell7, &battery3_cell8, &battery3_cell9, &battery3_cell10, &battery3_cell11, &battery3_cell12, &battery3_total_voltage, &battery3_max_temp, &battery3_min_temp);
    }

    static void battery_4_init(float &battery4_cell1, float &battery4_cell2, float &battery4_cell3, float &battery4_cell4, float &battery4_cell5, float &battery4_cell6, float &battery4_cell7, float &battery4_cell8, float &battery4_cell9, float &battery4_cell10, float &battery4_cell11, float &battery4_cell12, float &battery4_total_voltage, float &battery4_max_temp, float &battery4_min_temp)
    {
        battery_4_packet = new HeapPacket(static_cast<uint16_t>(913), &battery4_cell1, &battery4_cell2, &battery4_cell3, &battery4_cell4, &battery4_cell5, &battery4_cell6, &battery4_cell7, &battery4_cell8, &battery4_cell9, &battery4_cell10, &battery4_cell11, &battery4_cell12, &battery4_total_voltage, &battery4_max_temp, &battery4_min_temp);
    }

    static void battery_5_init(float &battery5_cell1, float &battery5_cell2, float &battery5_cell3, float &battery5_cell4, float &battery5_cell5, float &battery5_cell6, float &battery5_cell7, float &battery5_cell8, float &battery5_cell9, float &battery5_cell10, float &battery5_cell11, float &battery5_cell12, float &battery5_total_voltage, float &battery5_max_temp, float &battery5_min_temp)
    {
        battery_5_packet = new HeapPacket(static_cast<uint16_t>(914), &battery5_cell1, &battery5_cell2, &battery5_cell3, &battery5_cell4, &battery5_cell5, &battery5_cell6, &battery5_cell7, &battery5_cell8, &battery5_cell9, &battery5_cell10, &battery5_cell11, &battery5_cell12, &battery5_total_voltage, &battery5_max_temp, &battery5_min_temp);
    }

    static void battery_6_init(float &battery6_cell1, float &battery6_cell2, float &battery6_cell3, float &battery6_cell4, float &battery6_cell5, float &battery6_cell6, float &battery6_cell7, float &battery6_cell8, float &battery6_cell9, float &battery6_cell10, float &battery6_cell11, float &battery6_cell12, float &battery6_total_voltage, float &battery6_max_temp, float &battery6_min_temp)
    {
        battery_6_packet = new HeapPacket(static_cast<uint16_t>(915), &battery6_cell1, &battery6_cell2, &battery6_cell3, &battery6_cell4, &battery6_cell5, &battery6_cell6, &battery6_cell7, &battery6_cell8, &battery6_cell9, &battery6_cell10, &battery6_cell11, &battery6_cell12, &battery6_total_voltage, &battery6_max_temp, &battery6_min_temp);
    }

    static void battery_7_init(float &battery7_cell1, float &battery7_cell2, float &battery7_cell3, float &battery7_cell4, float &battery7_cell5, float &battery7_cell6, float &battery7_cell7, float &battery7_cell8, float &battery7_cell9, float &battery7_cell10, float &battery7_cell11, float &battery7_cell12, float &battery7_total_voltage, float &battery7_max_temp, float &battery7_min_temp)
    {
        battery_7_packet = new HeapPacket(static_cast<uint16_t>(916), &battery7_cell1, &battery7_cell2, &battery7_cell3, &battery7_cell4, &battery7_cell5, &battery7_cell6, &battery7_cell7, &battery7_cell8, &battery7_cell9, &battery7_cell10, &battery7_cell11, &battery7_cell12, &battery7_total_voltage, &battery7_max_temp, &battery7_min_temp);
    }

    static void battery_8_init(float &battery8_cell1, float &battery8_cell2, float &battery8_cell3, float &battery8_cell4, float &battery8_cell5, float &battery8_cell6, float &battery8_cell7, float &battery8_cell8, float &battery8_cell9, float &battery8_cell10, float &battery8_cell11, float &battery8_cell12, float &battery8_total_voltage, float &battery8_max_temp, float &battery8_min_temp)
    {
        battery_8_packet = new HeapPacket(static_cast<uint16_t>(917), &battery8_cell1, &battery8_cell2, &battery8_cell3, &battery8_cell4, &battery8_cell5, &battery8_cell6, &battery8_cell7, &battery8_cell8, &battery8_cell9, &battery8_cell10, &battery8_cell11, &battery8_cell12, &battery8_total_voltage, &battery8_max_temp, &battery8_min_temp);
    }

    static void general_state_machine_init(gsm_status &gsm_status)
    {
        general_state_machine_packet = new HeapPacket(static_cast<uint16_t>(940), &gsm_status);
    }

    static void driver_diagnosis_init(int32_t &driver_reading_period)
    {
        driver_diagnosis_packet = new HeapPacket(static_cast<uint16_t>(942), &driver_reading_period);
    }

    static void imd_init(imd_status &imd_status, float &imd_resistance, bool &imd_is_ok, float &imd_duty, float &imd_freq)
    {
        imd_packet = new HeapPacket(static_cast<uint16_t>(943), &imd_status, &imd_resistance, &imd_is_ok, &imd_duty, &imd_freq);
    }

    static void minimum_soc_init(float &minimum_soc)
    {
        minimum_soc_packet = new HeapPacket(static_cast<uint16_t>(945), &minimum_soc);
    }

    static void batteries_data_init(float &voltage_min, float &voltage_max, float &temp_min, float &temp_max)
    {
        batteries_data_packet = new HeapPacket(static_cast<uint16_t>(947), &voltage_min, &voltage_max, &temp_min, &temp_max);
    }

    static void contactor_status_init(bool &contactor_discharge, bool &contactor_precharge, bool &contactor_low, bool &contactor_high, bool &contactor_common_high)
    {
        contactor_status_packet = new HeapPacket(static_cast<uint16_t>(956), &contactor_discharge, &contactor_precharge, &contactor_low, &contactor_high, &contactor_common_high);
    }

    static void SOC_init(float &soc)
    {
        SOC_packet = new HeapPacket(static_cast<uint16_t>(990), &soc);
    }

    static void nested_state_machine_init(nested_sm_status &nested_sm_status)
    {
        nested_state_machine_packet = new HeapPacket(static_cast<uint16_t>(960), &nested_sm_status);
    }

    public:
    inline static HeapPacket *batteries_voltage_packet{nullptr};
    inline static HeapPacket *voltage_sensor_packet{nullptr};
    inline static HeapPacket *current_sensor_packet{nullptr};
    inline static HeapPacket *sdc_packet{nullptr};
    inline static HeapPacket *battery_1_packet{nullptr};
    inline static HeapPacket *battery_2_packet{nullptr};
    inline static HeapPacket *battery_3_packet{nullptr};
    inline static HeapPacket *battery_4_packet{nullptr};
    inline static HeapPacket *battery_5_packet{nullptr};
    inline static HeapPacket *battery_6_packet{nullptr};
    inline static HeapPacket *battery_7_packet{nullptr};
    inline static HeapPacket *battery_8_packet{nullptr};
    inline static HeapPacket *general_state_machine_packet{nullptr};
    inline static HeapPacket *driver_diagnosis_packet{nullptr};
    inline static HeapPacket *imd_packet{nullptr};
    inline static HeapPacket *minimum_soc_packet{nullptr};
    inline static HeapPacket *batteries_data_packet{nullptr};
    inline static HeapPacket *contactor_status_packet{nullptr};
    inline static HeapPacket *SOC_packet{nullptr};
    inline static HeapPacket *nested_state_machine_packet{nullptr};
    
    inline static DatagramSocket *control_station_udp{nullptr};
    

    static void start()
    {
        if (batteries_voltage_packet == nullptr) {
            PANIC("Packet batteries_voltage not initialized");
        }
        if (voltage_sensor_packet == nullptr) {
            PANIC("Packet voltage_sensor not initialized");
        }
        if (current_sensor_packet == nullptr) {
            PANIC("Packet current_sensor not initialized");
        }
        if (sdc_packet == nullptr) {
            PANIC("Packet sdc not initialized");
        }
        if (battery_1_packet == nullptr) {
            PANIC("Packet battery_1 not initialized");
        }
        if (battery_2_packet == nullptr) {
            PANIC("Packet battery_2 not initialized");
        }
        if (battery_3_packet == nullptr) {
            PANIC("Packet battery_3 not initialized");
        }
        if (battery_4_packet == nullptr) {
            PANIC("Packet battery_4 not initialized");
        }
        if (battery_5_packet == nullptr) {
            PANIC("Packet battery_5 not initialized");
        }
        if (battery_6_packet == nullptr) {
            PANIC("Packet battery_6 not initialized");
        }
        if (battery_7_packet == nullptr) {
            PANIC("Packet battery_7 not initialized");
        }
        if (battery_8_packet == nullptr) {
            PANIC("Packet battery_8 not initialized");
        }
        if (general_state_machine_packet == nullptr) {
            PANIC("Packet general_state_machine not initialized");
        }
        if (driver_diagnosis_packet == nullptr) {
            PANIC("Packet driver_diagnosis not initialized");
        }
        if (imd_packet == nullptr) {
            PANIC("Packet imd not initialized");
        }
        if (minimum_soc_packet == nullptr) {
            PANIC("Packet minimum_soc not initialized");
        }
        if (batteries_data_packet == nullptr) {
            PANIC("Packet batteries_data not initialized");
        }
        if (contactor_status_packet == nullptr) {
            PANIC("Packet contactor_status not initialized");
        }
        if (SOC_packet == nullptr) {
            PANIC("Packet SOC not initialized");
        }
        if (nested_state_machine_packet == nullptr) {
            PANIC("Packet nested_state_machine not initialized");
        }
        

        control_station_udp = new DatagramSocket("192.168.1.7",50400,"192.168.0.9",50400);
        
        Scheduler::register_task(50000, +[](){
            DataPackets::control_station_udp->send_packet(*DataPackets::batteries_voltage_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::voltage_sensor_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::current_sensor_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::sdc_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::battery_1_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::battery_2_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::battery_3_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::battery_4_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::battery_5_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::battery_6_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::battery_7_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::battery_8_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::general_state_machine_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::driver_diagnosis_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::imd_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::minimum_soc_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::batteries_data_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::contactor_status_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::SOC_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::nested_state_machine_packet);
            });
    }



};