#pragma once
#include "ST-LIB.hpp"

/*Data packets for HVBMS 
-AUTOGENERATED CODE, DO NOT MODIFY-*/
class DataPackets{
public:
    enum class gsm_status : uint8_t 
    {
        CONNECTING = 0,
        OPERATIONAL = 1,
        FAULT = 2,
    };
    enum class sdc_status : uint8_t 
    {
        ENGAGED = 0,
        DISENGAGED = 1,
    };
    enum class bms_status : uint8_t 
    {
        OK = 0,
        FAULT = 1,
    };
    
    
    static void battery_1_init(float &battery1_SOC, float &battery1_cell1, float &battery1_cell2, float &battery1_cell3, float &battery1_cell4, float &battery1_cell5, float &battery1_cell6, float &battery1_total_voltage, float &battery1_conv_rate)
    {
        battery_1_packet = new HeapPacket(static_cast<uint16_t>(910), &battery1_SOC, &battery1_cell1, &battery1_cell2, &battery1_cell3, &battery1_cell4, &battery1_cell5, &battery1_cell6, &battery1_total_voltage, &battery1_conv_rate);
    }
    
    static void battery_2_init(float &battery2_SOC, float &battery2_cell1, float &battery2_cell2, float &battery2_cell3, float &battery2_cell4, float &battery2_cell5, float &battery2_cell6, float &battery2_total_voltage, float &battery2_conv_rate)
    {
        battery_2_packet = new HeapPacket(static_cast<uint16_t>(911), &battery2_SOC, &battery2_cell1, &battery2_cell2, &battery2_cell3, &battery2_cell4, &battery2_cell5, &battery2_cell6, &battery2_total_voltage, &battery2_conv_rate);
    }
    
    static void battery_3_init(float &battery3_SOC, float &battery3_cell1, float &battery3_cell2, float &battery3_cell3, float &battery3_cell4, float &battery3_cell5, float &battery3_cell6, float &battery3_total_voltage, float &battery3_conv_rate)
    {
        battery_3_packet = new HeapPacket(static_cast<uint16_t>(912), &battery3_SOC, &battery3_cell1, &battery3_cell2, &battery3_cell3, &battery3_cell4, &battery3_cell5, &battery3_cell6, &battery3_total_voltage, &battery3_conv_rate);
    }
    
    static void battery_4_init(float &battery4_SOC, float &battery4_cell1, float &battery4_cell2, float &battery4_cell3, float &battery4_cell4, float &battery4_cell5, float &battery4_cell6, float &battery4_total_voltage, float &battery4_conv_rate)
    {
        battery_4_packet = new HeapPacket(static_cast<uint16_t>(913), &battery4_SOC, &battery4_cell1, &battery4_cell2, &battery4_cell3, &battery4_cell4, &battery4_cell5, &battery4_cell6, &battery4_total_voltage, &battery4_conv_rate);
    }
    
    static void battery_5_init(float &battery5_SOC, float &battery5_cell1, float &battery5_cell2, float &battery5_cell3, float &battery5_cell4, float &battery5_cell5, float &battery5_cell6, float &battery5_total_voltage, float &battery5_conv_rate)
    {
        battery_5_packet = new HeapPacket(static_cast<uint16_t>(914), &battery5_SOC, &battery5_cell1, &battery5_cell2, &battery5_cell3, &battery5_cell4, &battery5_cell5, &battery5_cell6, &battery5_total_voltage, &battery5_conv_rate);
    }
    
    static void battery_6_init(float &battery6_SOC, float &battery6_cell1, float &battery6_cell2, float &battery6_cell3, float &battery6_cell4, float &battery6_cell5, float &battery6_cell6, float &battery6_total_voltage, float &battery6_conv_rate)
    {
        battery_6_packet = new HeapPacket(static_cast<uint16_t>(915), &battery6_SOC, &battery6_cell1, &battery6_cell2, &battery6_cell3, &battery6_cell4, &battery6_cell5, &battery6_cell6, &battery6_total_voltage, &battery6_conv_rate);
    }
    
    static void battery_7_init(float &battery7_SOC, float &battery7_cell1, float &battery7_cell2, float &battery7_cell3, float &battery7_cell4, float &battery7_cell5, float &battery7_cell6, float &battery7_total_voltage, float &battery7_conv_rate)
    {
        battery_7_packet = new HeapPacket(static_cast<uint16_t>(916), &battery7_SOC, &battery7_cell1, &battery7_cell2, &battery7_cell3, &battery7_cell4, &battery7_cell5, &battery7_cell6, &battery7_total_voltage, &battery7_conv_rate);
    }
    
    static void battery_8_init(float &battery8_SOC, float &battery8_cell1, float &battery8_cell2, float &battery8_cell3, float &battery8_cell4, float &battery8_cell5, float &battery8_cell6, float &battery8_total_voltage, float &battery8_conv_rate)
    {
        battery_8_packet = new HeapPacket(static_cast<uint16_t>(917), &battery8_SOC, &battery8_cell1, &battery8_cell2, &battery8_cell3, &battery8_cell4, &battery8_cell5, &battery8_cell6, &battery8_total_voltage, &battery8_conv_rate);
    }
    
    static void battery_9_init(float &battery9_SOC, float &battery9_cell1, float &battery9_cell2, float &battery9_cell3, float &battery9_cell4, float &battery9_cell5, float &battery9_cell6, float &battery9_total_voltage, float &battery9_conv_rate)
    {
        battery_9_packet = new HeapPacket(static_cast<uint16_t>(918), &battery9_SOC, &battery9_cell1, &battery9_cell2, &battery9_cell3, &battery9_cell4, &battery9_cell5, &battery9_cell6, &battery9_total_voltage, &battery9_conv_rate);
    }
    
    static void battery_10_init(float &battery10_SOC, float &battery10_cell1, float &battery10_cell2, float &battery10_cell3, float &battery10_cell4, float &battery10_cell5, float &battery10_cell6, float &battery10_total_voltage, float &battery10_conv_rate)
    {
        battery_10_packet = new HeapPacket(static_cast<uint16_t>(919), &battery10_SOC, &battery10_cell1, &battery10_cell2, &battery10_cell3, &battery10_cell4, &battery10_cell5, &battery10_cell6, &battery10_total_voltage, &battery10_conv_rate);
    }
    
    static void battery_11_init(float &battery11_SOC, float &battery11_cell1, float &battery11_cell2, float &battery11_cell3, float &battery11_cell4, float &battery11_cell5, float &battery11_cell6, float &battery11_total_voltage, float &battery11_conv_rate)
    {
        battery_11_packet = new HeapPacket(static_cast<uint16_t>(920), &battery11_SOC, &battery11_cell1, &battery11_cell2, &battery11_cell3, &battery11_cell4, &battery11_cell5, &battery11_cell6, &battery11_total_voltage, &battery11_conv_rate);
    }
    
    static void battery_12_init(float &battery12_SOC, float &battery12_cell1, float &battery12_cell2, float &battery12_cell3, float &battery12_cell4, float &battery12_cell5, float &battery12_cell6, float &battery12_total_voltage, float &battery12_conv_rate)
    {
        battery_12_packet = new HeapPacket(static_cast<uint16_t>(921), &battery12_SOC, &battery12_cell1, &battery12_cell2, &battery12_cell3, &battery12_cell4, &battery12_cell5, &battery12_cell6, &battery12_total_voltage, &battery12_conv_rate);
    }
    
    static void battery_13_init(float &battery13_SOC, float &battery13_cell1, float &battery13_cell2, float &battery13_cell3, float &battery13_cell4, float &battery13_cell5, float &battery13_cell6, float &battery13_total_voltage, float &battery13_conv_rate)
    {
        battery_13_packet = new HeapPacket(static_cast<uint16_t>(922), &battery13_SOC, &battery13_cell1, &battery13_cell2, &battery13_cell3, &battery13_cell4, &battery13_cell5, &battery13_cell6, &battery13_total_voltage, &battery13_conv_rate);
    }
    
    static void battery_14_init(float &battery14_SOC, float &battery14_cell1, float &battery14_cell2, float &battery14_cell3, float &battery14_cell4, float &battery14_cell5, float &battery14_cell6, float &battery14_total_voltage, float &battery14_conv_rate)
    {
        battery_14_packet = new HeapPacket(static_cast<uint16_t>(923), &battery14_SOC, &battery14_cell1, &battery14_cell2, &battery14_cell3, &battery14_cell4, &battery14_cell5, &battery14_cell6, &battery14_total_voltage, &battery14_conv_rate);
    }
    
    static void battery_15_init(float &battery15_SOC, float &battery15_cell1, float &battery15_cell2, float &battery15_cell3, float &battery15_cell4, float &battery15_cell5, float &battery15_cell6, float &battery15_total_voltage, float &battery15_conv_rate)
    {
        battery_15_packet = new HeapPacket(static_cast<uint16_t>(924), &battery15_SOC, &battery15_cell1, &battery15_cell2, &battery15_cell3, &battery15_cell4, &battery15_cell5, &battery15_cell6, &battery15_total_voltage, &battery15_conv_rate);
    }
    
    static void battery_16_init(float &battery16_SOC, float &battery16_cell1, float &battery16_cell2, float &battery16_cell3, float &battery16_cell4, float &battery16_cell5, float &battery16_cell6, float &battery16_total_voltage, float &battery16_conv_rate)
    {
        battery_16_packet = new HeapPacket(static_cast<uint16_t>(925), &battery16_SOC, &battery16_cell1, &battery16_cell2, &battery16_cell3, &battery16_cell4, &battery16_cell5, &battery16_cell6, &battery16_total_voltage, &battery16_conv_rate);
    }
    
    static void battery_17_init(float &battery17_SOC, float &battery17_cell1, float &battery17_cell2, float &battery17_cell3, float &battery17_cell4, float &battery17_cell5, float &battery17_cell6, float &battery17_total_voltage, float &battery17_conv_rate)
    {
        battery_17_packet = new HeapPacket(static_cast<uint16_t>(926), &battery17_SOC, &battery17_cell1, &battery17_cell2, &battery17_cell3, &battery17_cell4, &battery17_cell5, &battery17_cell6, &battery17_total_voltage, &battery17_conv_rate);
    }
    
    static void battery_18_init(float &battery18_SOC, float &battery18_cell1, float &battery18_cell2, float &battery18_cell3, float &battery18_cell4, float &battery18_cell5, float &battery18_cell6, float &battery18_total_voltage, float &battery18_conv_rate)
    {
        battery_18_packet = new HeapPacket(static_cast<uint16_t>(927), &battery18_SOC, &battery18_cell1, &battery18_cell2, &battery18_cell3, &battery18_cell4, &battery18_cell5, &battery18_cell6, &battery18_total_voltage, &battery18_conv_rate);
    }
    
    static void batteries_voltage_init(float &batteries_voltage_reading)
    {
        batteries_voltage_packet = new HeapPacket(static_cast<uint16_t>(928), &batteries_voltage_reading);
    }
    
    static void voltage_sensor_init(float &voltage_reading)
    {
        voltage_sensor_packet = new HeapPacket(static_cast<uint16_t>(930), &voltage_reading);
    }
    
    static void current_sensor_init(float &current_reading)
    {
        current_sensor_packet = new HeapPacket(static_cast<uint16_t>(931), &current_reading);
    }
    
    static void general_state_machine_init(gsm_status &gsm_status)
    {
        general_state_machine_packet = new HeapPacket(static_cast<uint16_t>(940), &gsm_status);
    }
    
    static void driver_diagnosis_init(int32_t &driver_reading_period)
    {
        driver_diagnosis_packet = new HeapPacket(static_cast<uint16_t>(942), &driver_reading_period);
    }
    
    static void sdc_init(sdc_status &sdc_status)
    {
        sdc_packet = new HeapPacket(static_cast<uint16_t>(944), &sdc_status);
    }
    
    static void minimum_soc_init(float &minimum_soc)
    {
        minimum_soc_packet = new HeapPacket(static_cast<uint16_t>(945), &minimum_soc);
    }
    
    static void bms_init(bms_status &bms_status)
    {
        bms_packet = new HeapPacket(static_cast<uint16_t>(946), &bms_status);
    }
    
    static void batteries_data_init(float &voltage_min, float &voltage_max, float &temp_min, float &temp_max)
    {
        batteries_data_packet = new HeapPacket(static_cast<uint16_t>(947), &voltage_min, &voltage_max, &temp_min, &temp_max);
    }
    
    public:
    inline static HeapPacket *battery_1_packet{nullptr};
    inline static HeapPacket *battery_2_packet{nullptr};
    inline static HeapPacket *battery_3_packet{nullptr};
    inline static HeapPacket *battery_4_packet{nullptr};
    inline static HeapPacket *battery_5_packet{nullptr};
    inline static HeapPacket *battery_6_packet{nullptr};
    inline static HeapPacket *battery_7_packet{nullptr};
    inline static HeapPacket *battery_8_packet{nullptr};
    inline static HeapPacket *battery_9_packet{nullptr};
    inline static HeapPacket *battery_10_packet{nullptr};
    inline static HeapPacket *battery_11_packet{nullptr};
    inline static HeapPacket *battery_12_packet{nullptr};
    inline static HeapPacket *battery_13_packet{nullptr};
    inline static HeapPacket *battery_14_packet{nullptr};
    inline static HeapPacket *battery_15_packet{nullptr};
    inline static HeapPacket *battery_16_packet{nullptr};
    inline static HeapPacket *battery_17_packet{nullptr};
    inline static HeapPacket *battery_18_packet{nullptr};
    inline static HeapPacket *batteries_voltage_packet{nullptr};
    inline static HeapPacket *voltage_sensor_packet{nullptr};
    inline static HeapPacket *current_sensor_packet{nullptr};
    inline static HeapPacket *general_state_machine_packet{nullptr};
    inline static HeapPacket *driver_diagnosis_packet{nullptr};
    inline static HeapPacket *sdc_packet{nullptr};
    inline static HeapPacket *minimum_soc_packet{nullptr};
    inline static HeapPacket *bms_packet{nullptr};
    inline static HeapPacket *batteries_data_packet{nullptr};
    
    inline static ServerSocket *control_station_tcp{nullptr};
    inline static DatagramSocket *control_station_udp{nullptr};
    
        
    static void start()
    {   
        if (battery_1_packet == nullptr) {
            ErrorHandler("Packet battery_1 not initialized");
        }
        if (battery_2_packet == nullptr) {
            ErrorHandler("Packet battery_2 not initialized");
        }
        if (battery_3_packet == nullptr) {
            ErrorHandler("Packet battery_3 not initialized");
        }
        if (battery_4_packet == nullptr) {
            ErrorHandler("Packet battery_4 not initialized");
        }
        if (battery_5_packet == nullptr) {
            ErrorHandler("Packet battery_5 not initialized");
        }
        if (battery_6_packet == nullptr) {
            ErrorHandler("Packet battery_6 not initialized");
        }
        if (battery_7_packet == nullptr) {
            ErrorHandler("Packet battery_7 not initialized");
        }
        if (battery_8_packet == nullptr) {
            ErrorHandler("Packet battery_8 not initialized");
        }
        if (battery_9_packet == nullptr) {
            ErrorHandler("Packet battery_9 not initialized");
        }
        if (battery_10_packet == nullptr) {
            ErrorHandler("Packet battery_10 not initialized");
        }
        if (battery_11_packet == nullptr) {
            ErrorHandler("Packet battery_11 not initialized");
        }
        if (battery_12_packet == nullptr) {
            ErrorHandler("Packet battery_12 not initialized");
        }
        if (battery_13_packet == nullptr) {
            ErrorHandler("Packet battery_13 not initialized");
        }
        if (battery_14_packet == nullptr) {
            ErrorHandler("Packet battery_14 not initialized");
        }
        if (battery_15_packet == nullptr) {
            ErrorHandler("Packet battery_15 not initialized");
        }
        if (battery_16_packet == nullptr) {
            ErrorHandler("Packet battery_16 not initialized");
        }
        if (battery_17_packet == nullptr) {
            ErrorHandler("Packet battery_17 not initialized");
        }
        if (battery_18_packet == nullptr) {
            ErrorHandler("Packet battery_18 not initialized");
        }
        if (batteries_voltage_packet == nullptr) {
            ErrorHandler("Packet batteries_voltage not initialized");
        }
        if (voltage_sensor_packet == nullptr) {
            ErrorHandler("Packet voltage_sensor not initialized");
        }
        if (current_sensor_packet == nullptr) {
            ErrorHandler("Packet current_sensor not initialized");
        }
        if (general_state_machine_packet == nullptr) {
            ErrorHandler("Packet general_state_machine not initialized");
        }
        if (driver_diagnosis_packet == nullptr) {
            ErrorHandler("Packet driver_diagnosis not initialized");
        }
        if (sdc_packet == nullptr) {
            ErrorHandler("Packet sdc not initialized");
        }
        if (minimum_soc_packet == nullptr) {
            ErrorHandler("Packet minimum_soc not initialized");
        }
        if (bms_packet == nullptr) {
            ErrorHandler("Packet bms not initialized");
        }
        if (batteries_data_packet == nullptr) {
            ErrorHandler("Packet batteries_data not initialized");
        }
        

        control_station_tcp = new ServerSocket("192.168.1.7",50500);
        control_station_udp = new DatagramSocket("192.168.1.7",50400,"192.168.0.9",50400);
        
        
    }


   
};