#pragma once
#include "ST-LIB.hpp"

/*Order packets for HVBMS
-AUTOGENERATED CODE, DO NOT MODIFY- */


class OrderPackets{
public:
    

    inline static bool FAULT_flag{false};
    inline static bool open_contactors_flag{false};
    inline static bool start_precharge_flag{false};
    inline static bool bypass_imd_flag{false};
    

    OrderPackets() = default;

    inline static HeapOrder *FAULT_order{nullptr};
    inline static HeapOrder *open_contactors_order{nullptr};
    inline static HeapOrder *start_precharge_order{nullptr};
    inline static HeapOrder *bypass_imd_order{nullptr};
    

    static void FAULT_init()
    {
        FAULT_order = new HeapOrder(0, &FAULT_cb);
    }
    static void open_contactors_init()
    {
        open_contactors_order = new HeapOrder(901, &open_contactors_cb);
    }
    static void start_precharge_init()
    {
        start_precharge_order = new HeapOrder(903, &start_precharge_cb);
    }
    static void bypass_imd_init()
    {
        bypass_imd_order = new HeapOrder(904, &bypass_imd_cb);
    }
    

    
    inline static ServerSocket *control_station_tcp{nullptr};
    

    static void start()
    {
        if (FAULT_order == nullptr) {
            ErrorHandler("Order FAULT not initialized");
        }
        if (open_contactors_order == nullptr) {
            ErrorHandler("Order open_contactors not initialized");
        }
        if (start_precharge_order == nullptr) {
            ErrorHandler("Order start_precharge not initialized");
        }
        if (bypass_imd_order == nullptr) {
            ErrorHandler("Order bypass_imd not initialized");
        }
        

        control_station_tcp = new ServerSocket("192.168.1.7",50500);
        
    }

private:
    static void FAULT_cb()
    {
        FAULT_flag = true;
    }
    static void open_contactors_cb()
    {
        open_contactors_flag = true;
    }
    static void start_precharge_cb()
    {
        start_precharge_flag = true;
    }
    static void bypass_imd_cb()
    {
        bypass_imd_flag = true;
    }
    
};