#pragma once
#include "ST-LIB.hpp"

/*Order packets for HVBMS
-AUTOGENERATED CODE, DO NOT MODIFY- */


class OrderPackets{
public:
    

    inline static bool FAULT_flag{false};
    inline static bool open_contactors_flag{false};
    inline static bool cell_balance_flag{false};
    inline static bool start_precharge_flag{false};
    inline static bool check_faults_flag{false};
    

    OrderPackets() = default;

    inline static HeapOrder *FAULT_order{nullptr};
    inline static HeapOrder *open_contactors_order{nullptr};
    inline static HeapOrder *cell_balance_order{nullptr};
    inline static HeapOrder *start_precharge_order{nullptr};
    inline static HeapOrder *check_faults_order{nullptr};
    

    static void FAULT_init()
    {
        FAULT_order = new HeapOrder(0, &FAULT_cb);
    }
    static void open_contactors_init()
    {
        open_contactors_order = new HeapOrder(901, &open_contactors_cb);
    }
    static void cell_balance_init()
    {
        cell_balance_order = new HeapOrder(902, &cell_balance_cb);
    }
    static void start_precharge_init()
    {
        start_precharge_order = new HeapOrder(903, &start_precharge_cb);
    }
    static void check_faults_init()
    {
        check_faults_order = new HeapOrder(904, &check_faults_cb);
    }
    

    
    inline static ServerSocket *control_station_tcp{nullptr};
    

    static void start()
    {
        if (FAULT_order == nullptr) {
            PANIC("Order FAULT not initialized");
        }
        if (open_contactors_order == nullptr) {
            PANIC("Order open_contactors not initialized");
        }
        if (cell_balance_order == nullptr) {
            PANIC("Order cell_balance not initialized");
        }
        if (start_precharge_order == nullptr) {
            PANIC("Order start_precharge not initialized");
        }
        if (check_faults_order == nullptr) {
            PANIC("Order check_faults not initialized");
        }
        

        control_station_tcp = new ServerSocket("192.168.1.7",50500);
        
    }

private:
    static void FAULT_cb()
    {
        FAULT_flag = true;
    }
    static void open_contactors_cb()
    {
        open_contactors_flag = true;
    }
    static void cell_balance_cb()
    {
        cell_balance_flag = true;
    }
    static void start_precharge_cb()
    {
        start_precharge_flag = true;
    }
    static void check_faults_cb()
    {
        check_faults_flag = true;
    }
    
};