#pragma once
#include "ST-LIB.hpp"

/*Order packets for HVBMS 
-AUTOGENERATED CODE, DO NOT MODIFY- */


class OrderPackets{
public:
    

    inline static bool FAULT_flag{false};
    inline static bool close_contactors_flag{false};
    inline static bool open_contactors_flag{false};
    inline static bool sdc_obccu_flag{false};
    

    OrderPackets() = default;

    inline static HeapOrder *FAULT_order{nullptr};
    inline static HeapOrder *close_contactors_order{nullptr};
    inline static HeapOrder *open_contactors_order{nullptr};
    inline static HeapOrder *sdc_obccu_order{nullptr};
    
    
    static void FAULT_init()
    {
        FAULT_order = new HeapOrder(0, &FAULT_cb);
    }
    static void close_contactors_init()
    {
        close_contactors_order = new HeapOrder(900, &close_contactors_cb);
    }
    static void open_contactors_init()
    {
        open_contactors_order = new HeapOrder(901, &open_contactors_cb);
    }
    static void sdc_obccu_init()
    {
        sdc_obccu_order = new HeapOrder(902, &sdc_obccu_cb);
    }
    

private:
    static void FAULT_cb()
    {
        FAULT_flag = true;
    }
    static void close_contactors_cb()
    {
        close_contactors_flag = true;
    }
    static void open_contactors_cb()
    {
        open_contactors_flag = true;
    }
    static void sdc_obccu_cb()
    {
        sdc_obccu_flag = true;
    }
    
};